import { TaskNames } from '../constants';

export enum SubTaskNames {
  ERC20 = `${TaskNames.Generate}:erc20`,
  ERC721 = `${TaskNames.Generate}:erc721`,
}

export const RANDOM_TOKEN_METADATA = Object.entries({
  AAIGI: 'CryptoFlow',
  AKS: 'HyperSphere',
  ALEK: 'TechGraph',
  APWRB: 'CryptoStream',
  BJNXD: 'BlockShift',
  BLC: 'NovaMesh',
  BWQHU: 'VirtGraph',
  CEXQP: 'CyberNet',
  CEZHM: 'NetGraph',
  CLFVY: 'InfiMatrix',
  CXVRY: 'ChainMatrix',
  DBYE: 'ChainChain',
  DIT: 'MetaLedger',
  DWU: 'CryptoHub',
  DXV: 'BitLedger',
  EKVJ: 'TokenStream',
  ELQ: 'CryptoMesh',
  EOLDT: 'NanoZone',
  EQJDR: 'InfiLab',
  ESPDY: 'DeFiCore',
  FBEYF: 'NetTrade',
  FDDW: 'FinVerse',
  GBBW: 'BitMesh',
  GDHB: 'ChainSphere',
  GFQ: 'NanoFlow',
  GNZ: 'VirtX',
  HEEV: 'NovaVerse',
  HIO: 'CyberMatrix',
  HJDP: 'EtherZone',
  HTY: 'NetChain',
  INH: 'NovaNexus',
  IUSY: 'XenoNexus',
  JSX: 'ChainPay',
  JTBVN: 'CryptoNexus',
  KCG: 'VirtPay',
  KMHGY: 'NanoNet',
  KPJ: 'NovaHub',
  KUQU: 'MetaX',
  KVRF: 'DeFiMesh',
  LFO: 'BitChain',
  LKWPO: 'InfiGraph',
  LMDB: 'VirtHub',
  MAL: 'XenoMatrix',
  MEFSK: 'NetLedger',
  NBX: 'QuantumGraph',
  NDNEZ: 'BlockZone',
  NDVX: 'NetSphere',
  NFUC: 'ChainLab',
  NGZK: 'CyberNet',
  NQRO: 'HyperLab',
  OCZNB: 'TechGraph',
  OHBBJ: 'ChainChain',
  OQQSD: 'ChainShift',
  ORD: 'CryptoVerse',
  ORHPP: 'TechMesh',
  OYUQ: 'InfiLedger',
  OZZNW: 'CyberMatrix',
  PHXL: 'DeFiLab',
  PMU: 'QuantumPay',
  PSVIF: 'CyberLab',
  PTHCT: 'TechLedger',
  PZZ: 'QuantumVerse',
  QEA: 'CryptoStream',
  QEGAZ: 'TokenFlow',
  QULJ: 'TokenNexus',
  RDX: 'TokenShift',
  RGWXT: 'TechX',
  RNVCT: 'XenoStream',
  ROCS: 'NetShift',
  ROTL: 'XenoShift',
  RWQ: 'TechNet',
  RWWFV: 'VirtChain',
  RYHYG: 'CryptoChain',
  SANM: 'NanoHub',
  SPU: 'BlockSphere',
  SQJHF: 'EtherHub',
  SXADA: 'MetaNexus',
  TFJM: 'HyperX',
  UAK: 'NetLab',
  UAMB: 'NanoNexus',
  UJBCD: 'TokenLink',
  UKL: 'TechPay',
  ULDF: 'QuantumSphere',
  ULEJJ: 'FinPay',
  UUF: 'VirtTrade',
  VLT: 'NovaStream',
  WAW: 'XenoStream',
  WUOT: 'TechSphere',
  XAT: 'ChainVerse',
  XCXL: 'BitMatrix',
  XCY: 'CryptoSphere',
  XMDFV: 'CyberX',
  XNMM: 'ChainFlow',
  XTFBA: 'VirtNexus',
  YMWUY: 'NetFlow',
  YOE: 'CyberChain',
  YRB: 'NovaFlow',
  YZTQJ: 'BlockX',
  ZGS: 'EtherX',
  ZJDC: 'BlockChain',
});

export const RANDOM_TOKEN_METADATA_MIDDLE_INDEX = Math.ceil(
  RANDOM_TOKEN_METADATA.length / 2,
);
